%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_rpc_compile
-ifndef(MSG_H).
-define(MSG_H, true).

%%%===================================================================
%%% cmd
%%%===================================================================
-define(CMD_MSG_BASE_HEARTBEAT_REQ, 0). % mod_cmd:0 ccmd:0
-define(CMD_MSG_BASE_HEARTBEAT_RESP, 1). % mod_cmd:0 ccmd:1
-define(CMD_MSG_BASE_JUST_REQ, 2). % mod_cmd:0 ccmd:2

-ifdef(INCLUDE_ALL_PB_HRL).

-include("msg_base_pb.hrl").

-endif.

-endif.