%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.21.5

-ifndef(msg_pb).
-define(msg_pb, true).

-define(msg_pb_gpb_version, "4.21.5").



-endif.
