%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.21.5

-ifndef(msg_base_pb).
-define(msg_base_pb, true).

-define(msg_base_pb_gpb_version, "4.21.5").


-ifndef('HEARTBEAT_REQ_PB_H').
-define('HEARTBEAT_REQ_PB_H', true).
-record(heartbeat_req,
        {
        }).
-endif.

-ifndef('JUST_REQ_PB_H').
-define('JUST_REQ_PB_H', true).
-record(just_req,
        {id = 0                 :: non_neg_integer() | undefined % = 1, optional, 64 bits
        }).
-endif.

-ifndef('HEARTBEAT_RESP_PB_H').
-define('HEARTBEAT_RESP_PB_H', true).
-record(heartbeat_resp,
        {
        }).
-endif.

-ifndef('EMPTY_PB_H').
-define('EMPTY_PB_H', true).
-record(empty,
        {
        }).
-endif.

-endif.
